Authentication/urls.py
from django.urls import path, include
from Authentication.views import login_user, register_user, logout_user, get_pengunjung, login_flutter, logout_flutter, register_flutter

app_name = 'Authentication'

urlpatterns = [
    path('login/<str:status>/', login_user, name = 'login-user'),
    path('register/<str:status>', register_user, name = 'register-user'),
    path('logout/', logout_user, name = 'logout-user'),
    path('json/', get_pengunjung, name = 'json'),
    path('login_flutter', login_flutter, name = 'login_flutter'),
    path('logout_flutter', logout_flutter, name = 'logout_flutter'),
    path('register_flutter', register_flutter, name = 'register_flutter'),
]

Home/urls.py
from django.urls import path, include
from Home.views import show_home, show_json

app_name = 'Home'

urlpatterns = [
    path('', show_home, name = 'show_home'),
    path('jsoninfo/', show_json, name = 'show_json'),
]

faq/urls.py
from django.urls import path
from faq.views import *

app_name = 'faq'

urlpatterns = [
    path('', index, name='index'),
    path('create_question/', create_question, name='create_question'),
    path('json/', json, name='json')
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')), #(Steven) gw ngeubah yang tadinya default ke example jadi ke home
    path('Authentication/', include('Authentication.urls')), 
    path('faq/', include('faq.urls')),
    path('profile/', include('profilePage.urls')),
    path('donation/', include('donation.urls')),
    path('marketplace/', include('marketplace.urls')),
    path('partnership/', include('partnership.urls')),
]

# TODO: Implement Routings Here

Authentication/models.py
from django.db import models
from django.contrib.auth.models import User



# Create your models here.
class Pengunjung(models.Model):
    class JenisKelamin(models.TextChoices):
        laki_laki = 'LK', 'Male'
        perempuan = 'PP', 'Female'

    user = models.OneToOneField(User, on_delete = models.CASCADE, default = None)
    jenis_kelamin = models.CharField(max_length = 2, choices = JenisKelamin.choices, default = JenisKelamin.laki_laki)
    kontak = models.CharField(max_length = 13, blank = True)
    alamat = models.CharField(max_length = 100, blank = True)
    poin = models.IntegerField(default = 0)

Authentication/forms.py
from django import forms
from Authentication.models import Pengunjung
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

class NonAuthForm(forms.ModelForm):
    class Meta:
        model = Pengunjung
        fields = [
            'jenis_kelamin', 'kontak', 'alamat'
        ]
        labels = {
            'jenis_kelamin': 'Gender',
            'kontak': 'Contact',
            'alamat': 'Address'
        }
        widgets = {
            'jenis_kelamin': forms.Select(attrs = {
                'id': 'id_jenis_kelamin',
                'class': 'form-select'
            }),
            'kontak': forms.TextInput(attrs = {
                'id': 'id_kontak',
                'class': 'form-control',
                'aria-describedby': 'basic-addon1'
            }),
            'alamat': forms.TextInput(attrs = {
                'id': 'id_alamat',
                'class': 'form-control'
            })
        }

    def clean_kontak(self):
        kontak = self.cleaned_data['kontak']
        status = True
        for i in kontak:
            if not i.isdigit():
                status = False
                break
        if len(kontak) == 0:
            raise ValidationError("Contact Cannot Be Emptied")
        if not status:
            raise ValidationError("Contact Input Invalid")
        return kontak
    
    def clean_alamat(self):
        alamat = self.cleaned_data['alamat']
        if len(alamat) == 0:
            raise ValidationError("Address Cannot Be Emptied")
        return alamat

    

class ProfileForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs = {'id':'id_email'}))
    first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs = {'id':'id_first_name'}))
    last_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs = {'id':'id_last_name'}))
    
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')
    
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs = {
            'id': 'id_username',
            'class': 'form-control input-md',
            'placeholder': self.fields['username'].help_text
        }
        self.fields['password1'].widget.attrs = {
            'id': 'id_password1',
            'class': 'form-control',
            'placeholder': 'Type your password'
        }
        self.fields['password2'].widget.attrs = {
            'id': 'id_password2',
            'class': 'form-control',
            'placeholder': 'Re-type your password'
        }
        self.fields['first_name'].widget.attrs = {
            'id': 'id_first_name',
            'class': 'form-control'
        }
        self.fields['last_name'].widget.attrs = {
            'id': 'id_last_name',
            'class': 'form-control'
        }
        self.fields['email'].widget.attrs = {
            'id': 'id_email',
            'class': 'form-control input-lg',
            'aria-describedby': 'emailHelp',
            'required': 'required',
            'placeholder': 'example: john@gmail.com'
        }
    
    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        temp = User.objects.filter(email = email)
        if temp.count():
            raise ValidationError("Email Already Exists")
        return email

    def clean_first_name(self):
        first_name = self.cleaned_data['first_name'].upper()
        if not first_name.isalpha():
            raise ValidationError("First Name Invalid")
        return first_name
    
    def clean_last_name(self):
        last_name = self.cleaned_data['last_name'].upper()
        if not last_name.isalpha():
            raise ValidationError("Last Name Invalid")
        return last_name

class LoginForm(forms.Form):
    email = forms.EmailField(max_length = 75, widget = forms.EmailInput(attrs = {
        'id': 'id_email',
        'class': "form-control",
        'aria-describedby': 'emailHelp',
        'required': 'required',
        'placeholder': 'example: john@gmail.com'
    }))
    password = forms.CharField(widget = forms.PasswordInput(attrs = {
        'id': 'id_password',
        'class': 'form-control',
        'required': 'required',
        'placeholder': 'Min. 8 Alphanumeric Characters'
    }))

Authentication/views.py
import datetime
from django.shortcuts import render
from django.contrib.auth import login, authenticate, logout
from Authentication.models import Pengunjung
from Authentication.forms import ProfileForm, NonAuthForm, LoginForm
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseRedirect, JsonResponse
from django.db import transaction
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
# Create your views here.

@transaction.atomic
def register_user(request, status):
    if status == 'admin' or status == 'regular':
        if request.method == "POST":
            auth = ProfileForm({
                'username':request.POST.get('username'),
                'first_name':request.POST.get('first_name').upper(),
                'last_name':request.POST.get('last_name').upper(),
                'email':request.POST.get('email'),
                'password1':request.POST.get('password1'),
                'password2':request.POST.get('password2')
            })  
            if auth.is_valid():
                user = auth.save(commit = False)
                user.set_password(request.POST.get('password1'))
                non_auth = NonAuthForm({
                    'jenis_kelamin':request.POST.get('jenis_kelamin'),
                    'kontak':request.POST.get('kontak'),
                    'alamat':request.POST.get('alamat')
                })
                if non_auth.is_valid():
                    profile = non_auth.save(commit = False)
                    profile.user = user
                    if status == 'admin':
                        user.is_staff = True
                    user.save()
                    profile.save()
                    return HttpResponse('Account has successfully created !')
                else:
                    one = list(non_auth.errors.values())[0]
                    return HttpResponse(one)
            else:
                one = list(auth.errors.values())[0]
                return HttpResponse(one)
        auth = ProfileForm()
        non_auth = NonAuthForm()
        context = {
            'auth': auth,
            'non_auth': non_auth,
            'status': status
        }
        return render(request, 'register.html', context = context)
    else:
        return HttpResponseNotFound()

def login_user(request, status):
    if status == 'regular' or status == 'admin':
        if request.method == "POST":
            email = request.POST.get('email')
            password = request.POST.get('password')
            try:
                temp = User.objects.get(email = email)
                if (temp.is_staff == True and status == 'admin') or\
                    (temp.is_staff == False and status == 'regular'):
                    user = authenticate(request, username = temp.get_username(), password = password)
                    if user is not None:
                        login(request, user)
                        response = HttpResponse('Login Success')
                        response.set_cookie('last_login', str(datetime.datetime.now()))
                        return response
                    else:
                        raise Exception()
                else:
                    raise Exception()
            except:
                return HttpResponse('User Not Registered')

        auth = LoginForm()
        context = {
            'auth': auth,
            'status': status
        }
        return render(request, 'login.html', context = context)
    else:
        return HttpResponseNotFound()

def logout_user(request):
    status = 'regular'
    if request.user.is_staff:
        status = 'admin'
    logout(request)
    response = HttpResponseRedirect(reverse('Authentication:login-user', args = [status]))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/Authentication/login/regular')
def get_pengunjung(request):
    first_name = request.user.first_name.upper()
    last_name = request.user.last_name.upper()
    pengunjung = Pengunjung.objects.get(user = request.user)
    load = {
        'first_name': first_name,
        'last_name': last_name,
        'gender': pengunjung.jenis_kelamin,
        'coins': pengunjung.poin,
        'address' : pengunjung.alamat,
        'contact' : pengunjung.kontak,
    }
    return JsonResponse(load, safe = False)

@csrf_exempt
def login_flutter(request):
    email = request.POST.get('email')
    password = request.POST.get('password')
    try:
        temp = User.objects.get(email = email)
        user = authenticate(request, username = temp.get_username(), password = password)
        if user is not None:
            login(request, user)
            return JsonResponse({
               "status": True,
               "message": "Successfully Logged In!"
               # Insert any extra data if you want to pass data to Flutter
             }, status=200)
        else:
            return JsonResponse({
               "status": False,
               "message": "Failed to Login, Account Disabled."
             }, status=401)
    except:
        return JsonResponse({
           "status": False,
           "message": "Failed to Login, check your email/password."
         }, status=401)

@csrf_exempt
def logout_flutter(request):
    logout(request)
    return JsonResponse({
        "status": True,
        "message": "Successfully Logged Out!"
        # Insert any extra data if you want to pass data to Flutter
        }, status=200)

@csrf_exempt
def register_flutter(request):
    if request.method == "POST":
        auth = ProfileForm({
                    'username':request.POST.get('username'),
                    'first_name':request.POST.get('first_name').upper(),
                    'last_name':request.POST.get('last_name').upper(),
                    'email':request.POST.get('email'),
                    'password1':request.POST.get('password1'),
                    'password2':request.POST.get('password2')
                })  

        if auth.is_valid():
            user = auth.save(commit = False)
            user.set_password(request.POST.get('password1'))
            non_auth = NonAuthForm({
                'jenis_kelamin':request.POST.get('jenis_kelamin'),
                'kontak':request.POST.get('kontak'),
                'alamat':request.POST.get('alamat')
            })
            if non_auth.is_valid():
                profile = non_auth.save(commit = False)
                profile.user = user
                user.save()
                profile.save()
                return JsonResponse({
                "status": True,
                "message": "Account has successfully created !"
                }, status=200)
            else:
                one = list(non_auth.errors.values())[0]
                return JsonResponse({
                "status": False,
                "message": one
                }, status=401)
        else:
            one = list(auth.errors.values())[0]
            return JsonResponse({
                "status": False,
                "message": one
                }, status=401)
    else:
        return JsonResponse({
                "status": False,
                "message": "401 Error"
                }, status=401)

Authentication/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Authentication</title>

{% load static %}
<link rel="stylesheet" href="{% static '/authentication/css/login-style.css' %}">
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
{% endblock meta %}

{% block content %}
<!-- NAVBAR -->
<!-- <nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'Home:show_home' %}">Irama Kain</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="#">Shop</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'faq:index' %}" >FaQ</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Partnership</a>
        </li>
      </ul>
    </div>
  </div>
</nav> -->

<script>
  var temp2 = '{{status}}';
  var csrf = '{{csrf_token}}';
  var temp = "{% url 'Authentication:login-user' 1 %}".replace('1', temp2);
  var jsonUrl = "{% url 'Authentication:json' %}";
  var manUrl = "{% static '/authentication/img/man.jpg' %}";
  var womanUrl = "{% static '/authentication/img/woman.jpg' %}";
  var redirectUrl = "{% url 'Home:show_home' %}";
  var redirectUrlRegister = "{% url 'Authentication:register-user' 1 %}".replace('1', temp2);
</script>

<script type="text/JavaScript" src="{% static '/authentication/js/loginScript.js' %}"></script>

<div id="carouselControls" class="carousel slide" data-bs-interval="false">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <div class = 'd-flex flex-column min-vh-100 justify-content-center align-items-center' id = 'main_container'> 
        <div class="card mb-3 shadow-lg" id = myCard>
            <div class="row g-0">
              <div class="col-md-4" id = 'card_image_col'>
                <img src="{% static '/authentication/img/irama_kain.png' %}" class="img-fluid rounded-start" id = 'card_image'>
              </div>
              <div class="col-md-8">
                <div class="card-body" id = 'card_body'>
                  <h1 class="card-title" id = 'card_title' style = 'font-family: Stratford; color: #7335C2;'>Irama Kain</h1>
                  <form id = 'form-login'>
                    <div class="mb-3">
                      <label for="id_email" class="form-label">Email address</label>
                      {{auth.email}}
                      <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
                    </div>
                    <div class="mb-3">
                      <label for="id_password" class="form-label">Password</label>
                      {{auth.password}}
                    </div>
                    <label for = '#registerLink'>Don't have an account?</label>
                    <a href = '#'  id = "registerLink">register<br></a>
                    <button type="button" class="btn btn-outline-light" id = 'submit_button'>Login</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
    </div>
    <div class="carousel-item">
      <div id = "next-item">
        <div class = 'd-flex flex-column min-vh-100 justify-content-center align-items-center' id = 'main_container_2'> 
          <div class="card mb-3 shadow-lg" id = myCard_2>
              <div class="row g-0">
                <div class="col-md-4" id = 'card_image_col_2'>
                  <img src="{% static '/authentication/img/irama_kain.png' %}" class="img-fluid rounded-start" id = 'card_image_2'>
                </div>
                <div class="col-md-8">
                  <div class="card-body" id = 'card_body_2'>
                    <h1 class="card-title" id = 'card_title_2' style = 'font-family: Stratford; color: #7335C2;'></h1>
                  </div>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- <div class = 'container-fluid' id = 'container_footer'>
  <div class = 'row row-cols-auto justify-content-center' style = 'font-family:Stratford;color: #7335C2;height: 70px; padding-top: 10px;' id = 'row1_footer'>
    <div class = 'col-md-4' style = 'height: fit-content; width: 30px;'>
      <button type = 'button' class = 'btn btn-link'><img src = "{% static '/authentication/img/facebook.png' %}" style = 'height: 20px; width: 20px;'></a>
    </div>  
    <div class = 'col-md-4' style = 'height: fit-content; width: 30px; margin-left: 20px;'>
      <button type = 'button' class = 'btn btn-link'><img src = "{% static '/authentication/img/linked_in.png' %}" style = 'height: 20px; width: 20px;'></a>
    </div>
    <div class = 'col-md-4' style = 'height: fit-content; width: 30px; margin-left: 20px;'>
      <button type = 'button' class = 'btn btn-link'><img src = "{% static '/authentication/img/twitter.png' %}" style = 'height: 20px; width: 20px;'></a>
    </div>
    <div class = 'col-md-4' style = 'height: fit-content; width: 30px; margin-left: 20px;'>
      <button type = 'button' class = 'btn btn-link'><img src = "{% static '/authentication/img/amazon.png' %}" style = 'height: 20px; width: 20px;'></a>
    </div>
    <div class = 'col-md-4' style = 'height: fit-content; width: 30px; margin-left: 20px;'>
      <button type = 'button' class = 'btn btn-link'><img src = "{% static '/authentication/img/instagram_baru.png' %}" style = 'height: 20px; width: 20px;'></a>
    </div>
  </div>
  <div class = 'row row-cols-auto justify-content-center' id = 'row2_footer'>
    <p style = 'margin-left: 40px;'>©️2022 Copyright: Irama Kain</p>
  </div>
</div> -->

<script>
  if (temp2 === 'admin'){
    $("#card_title").append('<br>(admin)');
  }
  $('#registerLink').attr('href', redirectUrlRegister);
  // $('#carouselControls').carousel();
  // $('#carouselControls').carousel('pause');
</script>
{% endblock content %}

Authentication/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Authentication</title>
<link rel="stylesheet" href="{% static '/authentication/css/register-style.css' %}">
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
{% endblock meta %}

{% block content %}
<script>
    var csrf = '{{csrf_token}}';
    var temp2 = '{{status}}';
    var temp = "{% url 'Authentication:register-user' 1 %}".replace('1', temp2);
    var redirectUrl = "{% url 'Authentication:login-user' 1 %}".replace('1', temp2);
</script>
<script type = "text/JavaScript" src = "{% static '/authentication/js/registerScript.js' %}"></script>

<!-- NAVBAR -->
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'Home:show_home' %}">Irama Kain</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="#">Shop</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'faq:index' %}" >FaQ</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Partnership</a>
          </li>
        </ul>
      </div>
    </div>
</nav>

<div class = 'd-flex flex-column min-vh-100 justify-content-center align-items-center' id = 'main_container'> 
  <div class="card mb-3 shadow-lg" style="max-width: 1000px;" id = myCard>
      <div class="row">
        <div class="col justify-content-center">
          <div class="card-body" id = 'card_body'>
            <h3 class="card-title" id = 'card_title' style = 'font-family: Stratford; color: #7335C2;'>Create Account</h3>
            <div class = 'form-group row'>
              <label for = '#id_username'>{{auth.username.label}}</label>
              {{auth.username}}
            </div>
            <div class = 'form-group row'>
              <label for = '#id_email'>{{auth.email.label}}</label>
              {{auth.email}}
            </div>
            <div class = 'form-group row'>
              <div class = 'col'>
                <label for = '#id_first_name'>{{auth.first_name.label}}</label>
                {{auth.first_name}}
              </div>
              <div class = 'col'>
                <label for = '#id_last_name'>{{auth.last_name.label}}</label>
              {{auth.last_name}}
              </div>
            </div>
            <div class = 'form-group row'>
              <div class = 'col'>
                <label for = '#id_password1'>{{auth.password1.label}}</label>
                {{auth.password1}}
              </div>
              <div class = 'col'>
                <label for = '#id_password2'>{{auth.password2.label}}</label>
                {{auth.password2}}
              </div>
            </div>
            <div class = 'form-group row'>
              <div class = 'col'>
                <label for = '#id_jenis_kelamin'>{{non_auth.jenis_kelamin.label}}</label>
                {{non_auth.jenis_kelamin}}
              </div>
              <div class = 'col'>
                <label for = '#id_kontak'>{{non_auth.kontak.label}}</label>
                <div class="input-group mb-3">
                  <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1">+62</span>
                  </div>
                  {{non_auth.kontak}}
                </div>
              </div>
            </div>
            <div class = 'form-group row'>
              <label for = '#id_alamat'>{{non_auth.alamat.label}}</label>
              {{non_auth.alamat}}
            </div>
            
            <div class = 'form-check' style = 'margin-top: 20px;'>
              <input class="form-check-input" type="checkbox" value="" id="flexCheck">
              <label class="form-check-label" for="#flexCheck">
                I agree all statements in Terms of service
              </label>
            </div>
            <div class = 'form-group row justify-content-center'>
              <button type = 'button' class = 'btn btn-outline-light' id = "submit_button">Register</button>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>

<!-- <div class = 'container-fluid' id = 'container_footer'>
    <div class = 'row row-cols-auto justify-content-center' style = 'font-family:Stratford;color: #7335C2;height: 70px; padding-top: 10px;' id = 'row1_footer'>
      <div class = 'col-md-4' style = 'height: fit-content; width: 30px;'>
        <button type = 'button' class = 'btn btn-link'><img src = "{% static '/authentication/img/facebook.png' %}" style = 'height: 20px; width: 20px;'></a>
      </div>  
      <div class = 'col-md-4' style = 'height: fit-content; width: 30px; margin-left: 20px;'>
        <button type = 'button' class = 'btn btn-link'><img src = "{% static '/authentication/img/linked_in.png' %}" style = 'height: 20px; width: 20px;'></a>
      </div>
      <div class = 'col-md-4' style = 'height: fit-content; width: 30px; margin-left: 20px;'>
        <button type = 'button' class = 'btn btn-link'><img src = "{% static '/authentication/img/twitter.png' %}" style = 'height: 20px; width: 20px;'></a>
      </div>
      <div class = 'col-md-4' style = 'height: fit-content; width: 30px; margin-left: 20px;'>
        <button type = 'button' class = 'btn btn-link'><img src = "{% static '/authentication/img/amazon.png' %}" style = 'height: 20px; width: 20px;'></a>
      </div>
      <div class = 'col-md-4' style = 'height: fit-content; width: 30px; margin-left: 20px;'>
        <button type = 'button' class = 'btn btn-link'><img src = "{% static '/authentication/img/instagram_baru.png' %}" style = 'height: 20px; width: 20px;'></a>
      </div>
    </div>
    <div class = 'row row-cols-auto justify-content-center' id = 'row2_footer'>
      <p style = 'margin-left: 40px;'>©️2022 Copyright: Irama Kain</p>
    </div>
</div> -->
{% endblock content %}