Home/urls.py
from django.urls import path, include
from Home.views import show_home, show_json

app_name = 'Home'

urlpatterns = [
    path('', show_home, name = 'show_home'),
    path('jsoninfo/', show_json, name = 'show_json'),
]

donation/urls.py
# TODO: Implement Routings Here
from django.urls import path
from .views import *

app_name = 'donation'

urlpatterns = [
    path('', show_donation, name='show-donation'),
    path('form/', form_donation, name='form-donation'),
    path('json/', show_json, name='show_json'),
    path('history/', show_alltime_donation, name='show_alltime_donation'),
    path('done/<int:id>', selesai_donasi, name='done'),
    path('edit/<int:id>', edit_donasi, name='edit'),
    path('edit_flutter/<int:id>', edit_flutter, name='edit_flutter'),
    path('form_flutter/', form_flutter, name='form_flutter'),
    path('current/<int:id>', get_current_donation, name='current'),






]

faq/urls.py
from django.urls import path
from faq.views import *

app_name = 'faq'

urlpatterns = [
    path('', index, name='index'),
    path('create_question/', create_question, name='create_question'),
    path('json/', json, name='json')
]

marketplace/urls.py
# TODO: Implement Routings Here
from django.urls import path
from .views import *

app_name = 'marketplace'

urlpatterns = [
    path('', show_marketplace, name='show_marketplace'),
    path('form', form_marketplace, name='form_marketplace'),
    path('beli_flutter', beli_flutter, name='beli_flutter'),
    path('get_pembelian_flutter', get_pembelian_flutter, name='get_pembelian_flutter'),
]

partnership/urls.py
from django.urls import path
from partnership.views import CommentView, CommentDataView

app_name = 'partnership'

urlpatterns = [
    path('', CommentView.as_view(), name="comment"),
    path('view', CommentDataView.as_view(), name="comment_data")
]

profilePage/urls.py
from django.urls import path
from .views import *

app_name = 'profilePage'

urlpatterns = [
    path('', lihatProfile, name='lihatProfile'),
    path('edit/', editProfile, name='editProfile'),
    path('get_profile', get_profile, name = 'getProfile'),
    path('edit_flutter', edit_flutter, name = 'editFlutter'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')), #(Steven) gw ngeubah yang tadinya default ke example jadi ke home
    path('Authentication/', include('Authentication.urls')), 
    path('faq/', include('faq.urls')),
    path('profile/', include('profilePage.urls')),
    path('donation/', include('donation.urls')),
    path('marketplace/', include('marketplace.urls')),
    path('partnership/', include('partnership.urls')),
]

# TODO: Implement Routings Here

donation/models.py
from email.policy import default
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from Authentication.models import Pengunjung
from datetime import datetime
from django.utils.timezone import now

# Create your models here.

KURIR_CHOICES = (
    ('Antar sendiri', "Antar sendiri"), ('JNE', 'JNE'), ('POS INDONESIA', 'POS INDONESIA'), ('TIKI', 'TIKI'), ('SiCepat', 'SiCepat'), ('J&T', 'J&T')
)
class DonationInfo(models.Model):
   
    pengunjung = models.ForeignKey(Pengunjung, null = True, on_delete = models.CASCADE)
    waktu_isi = models.DateTimeField(default = now)
    jenis_barang = models.CharField(max_length=255, verbose_name= "Jenis Kain")
    amount = models.IntegerField(verbose_name = "Banyak (dalam kg)")
    shipping_method = models.CharField(max_length = 255, choices = KURIR_CHOICES, default= KURIR_CHOICES[0], verbose_name= "Metode pengiriman")
    is_done = models.BooleanField(default = False)

donation/forms.py
from django import forms
from donation import models




class DonationForm(forms.ModelForm) :
    class Meta:
        model = models.DonationInfo
        fields = ['jenis_barang', 'amount', 'shipping_method']
        jenis_barang = forms.CharField(max_length=255)
        amount = forms.IntegerField()
        shipping_method = forms.ChoiceField()
        

        

donation/views.py
from django.utils.timezone import now
from django.shortcuts import redirect, render
from django.http import HttpResponse, HttpResponseNotFound, JsonResponse
from django.core import serializers
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from donation.forms import DonationForm
from Authentication.models import Pengunjung
from donation.models import DonationInfo
from django.views.decorators.csrf import csrf_exempt

# TODO:implement views

def form_donation(request):
    if request.user.is_authenticated:
        data_pengunjung = Pengunjung.objects.get(user=request.user)
        form = DonationForm()
        if (request.method == 'POST'):
            form = DonationForm(request.POST)
            if form.is_valid():
                temp = form.save(commit=False)
                print(request.user)
                temp.pengunjung = Pengunjung.objects.get(user = request.user)
                form.save()
                return redirect('/donation/')

        context = {
            'form' : form,
            'poin' : data_pengunjung.poin

        }
        return render(request, "donationForm.html", context)
    else:
        return render(request, "notauth.html")

@login_required(login_url='../Authentication/login/<str:status>/')
def show_json(request):
    data_pengunjung = Pengunjung.objects.get(user=request.user)
    data = DonationInfo.objects.filter(pengunjung=data_pengunjung, is_done = False)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@login_required(login_url='../Authentication/login/<str:status>/')
def show_alltime_donation(request):
    data_pengunjung = Pengunjung.objects.get(user=request.user)
    data_alltime = DonationInfo.objects.filter(pengunjung= data_pengunjung, is_done = True)
    return HttpResponse(serializers.serialize("json", data_alltime), content_type="application/json")


@login_required(login_url='../Authentication/login/<str:status>/')
@csrf_exempt
def selesai_donasi(request, id):
    data_pengunjung = Pengunjung.objects.get(user=request.user)
    data = DonationInfo.objects.get(pk=id)
    data.is_done = True
    tambah_poin = 3000*data.amount
    print(data_pengunjung.poin)
    data_pengunjung.poin += tambah_poin
    data_pengunjung.save()
    data.save()
    content = {
        'poin' : data_pengunjung.poin
    }
    return JsonResponse(content, safe=False)

@login_required(login_url='../Authentication/login/<str:status>/')
@csrf_exempt
def edit_donasi(request, id):
    print(id)
    if request.method == 'POST':
        jenis_barang = request.POST.get("jenis_barang")
        waktu_isi = now()
        amount = request.POST.get("amount")
        shipping_method = request.POST.get("shipping_method")
        data = DonationInfo.objects.get(pk=id)
        data.jenis_barang = jenis_barang
        data.amount = amount
        data.waktu_isi = waktu_isi
        data.shipping_method = shipping_method
        data.save()
        # print(data)
        print(DonationInfo.objects.filter(pk=id).values())
        return HttpResponse(b"CREATED", status=201)
    return HttpResponseNotFound()

def show_donation(request):
    if request.user.is_authenticated:
        data_pengunjung = Pengunjung.objects.get(user=request.user)
        form_donation = DonationForm()
        context = {
            'user_name' : data_pengunjung.user.first_name,
            'alamat' : data_pengunjung.alamat,
            'kontak' : data_pengunjung.kontak,
            'form_donation' : form_donation, 
            'poin' : data_pengunjung.poin
        
        }
        return render(request, "donationHistory.html", context)
    else:
        return render(request, "notauth.html")

@login_required(login_url='../Authentication/login/<str:status>/')
@csrf_exempt
def edit_flutter(request, id):
    print(id)
    if request.method == 'POST':
        jenis_barang = request.POST.get("jenis_barang")
        waktu_isi = now()
        amount = request.POST.get("amount")
        shipping_method = request.POST.get("shipping_method")
        data = DonationInfo.objects.get(pk=id)
        data.jenis_barang = jenis_barang
        data.amount = amount
        data.waktu_isi = waktu_isi
        data.shipping_method = shipping_method
        data.save()
        # print(data)
        print(DonationInfo.objects.filter(pk=id).values())
        return JsonResponse({
                "status": True,
                "message": "Successfully edited donation"
                }, status=200)
    return JsonResponse({
                "status": False,
                "message": "401 Error"
                }, status=401)

@login_required(login_url='../Authentication/login/<str:status>/')
@csrf_exempt
def form_flutter(request):
    if request.user.is_authenticated:
        data_pengunjung = Pengunjung.objects.get(user=request.user)
        form = DonationForm()
        if (request.method == 'POST'):
            form = DonationForm(request.POST)
            if form.is_valid():
                temp = form.save(commit=False)
                print(request.user)
                temp.pengunjung = Pengunjung.objects.get(user = request.user)
                form.save()
                return JsonResponse({
                "status": True,
                "message": "Successfully added donation"
                }, status=200)
        return JsonResponse({
                "status": False,
                "message": "401 Error"
                }, status=401)
    else:
        return JsonResponse({
                "status": False,
                "message": "401 Error"
                }, status=401)

@login_required(login_url='../Authentication/login/<str:status>/')
@csrf_exempt
def get_current_donation(request, id):
    data = DonationInfo.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

donation/templates/donationForm.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Donation | Irama Kain</title>
{% endblock meta %}

{% block content %}
<html>
    <head>
        <link rel="stylesheet" href= "{% static "/donation/css/donationform.css" %}">
    </head>
    <body>
        <!-- NAVBAR -->
        
          <!-- END NAVBAR -->
        
        <form method="POST" action="">
            {% csrf_token %} {% for hidden_field in form.hidden_fields %}
            {{ hidden_field }}
          {% endfor %}
        <div class="donationbox">
            <h1 class="texth1" >Form Donasi</h1>
            {% for field in form.visible_fields %}
                <div class="form-group">
                {{ field.label_tag }}
                {{ field }}
                {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
                </div>
            {% endfor %}
                    <div class="row buttoncontainer">
                        <input  class="col buttonsubmit" type="submit" name="submit" value="Save" class = "button btn btn-primary"/>
                    </div>
            </form>
        </div>
    </body>
</html>
{% endblock content %}

donation/templates/donationHistory.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Donation | Irama Kain</title>
{% endblock meta %}

{% block content %}
<html>
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href= "{% static "/donation/css/donationhistory.css" %}">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        
        <style>
            .card-horizontal {
            display: flex;
            flex: auto;
            }
            .photo  {
                width: 200px;
                height: 200px;
            }
        </style>
    </head>
    <body>
        <script>
            var csrf = '{{ csrf_token }}';
            var kontak = '{{kontak}}';
            var alamat = '{{alamat}}';
            var imgcard = '{% static "/donation/img/unsplash_fouVDmGXoPI.png" %}'
        </script>
        <script
            type="text/javascript"
            src ="{% static 'donation/js/donationhistory.js' %}">
        </script>
        <!-- NAVBAR -->
        <nav class="navbar navbar-expand-lg">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'Home:show_home' %}">Irama Kain</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'donation:show-donation' %} ">Donations</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'marketplace:show_marketplace' %} ">Shop</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'faq:index' %}" >F.A.Q</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href='{% url "partnership:comment"  %}' >Contact Us</a>
                  </li>
                  <li class="nav-item" id="linkprofile">
                    <a class="nav-link" href="{% url 'profilePage:lihatProfile' %}">Profile</a>
                  </li>
                </ul>
                <div class="d-flex">
                    <a class="nav-link" href="#" style="margin-right: 20px">
                        <img class="me-2 p-2 nav-item" src="../static/donation/img/cart.png" style="width: 40px; height:40px; ">
                    </a>
                    <div  class="containers col p-2" style="padding-top: 12px; margin-left: 10px; margin-right: 30px;">
                        <img src="../static/profile/img/Coins.png" style="display: inline; width: 25px; height: 25px; margin-bottom: 10px">
                        <p id="linkpoin" class="nav-link" style="display: inline; font-size: 16px;">{{poin}}</p>
                    </div>
                    <a class="p-2 nav-link" id="linksignout" href="{% url 'Authentication:logout-user' %}">Sign Out</a>
                </div>
              </div>
            </div>
        </nav>
          <!-- END NAVBAR -->
          <div class="donation">
            <div class = "photo-group">
                <div class="col sea-group" id="seagroup">
                    <div class="row" style="float:right; width:600px; padding-right:20px">
                        <div class="col" id="batasAtas"></div>
                        <div class="w-100"></div>
                        <div class="sea">
                            <div class="sea-bg row">
                                <div class="col linearmove waveshort">
                                    <img class="sea-item" src="../static/donation/img/cloth.png">
                                </div>
                                <div class="col linearmove wave2">
                                    <img class="sea-item" src="../static/donation/img/bottle.png">
                                    <img class="sea-item" src="../static/donation/img/plastic.png">
                                </div>
                                <div class="col linearmove wave3">
                                    <img class= "sea-item" src="../static/donation/img/sandal.png">
                                    <img class="sea-item" src="../static/donation/img/fishbone.png">
                                </div>
                            </div>
                        </div>
                        <div class="w-100"></div>
                        <div class="col" id="batasBawah"></div>
                    </div>
                </div>
                <div class="text-group">
                    <p class="text-photo" id="paragraph1">
                        Microplastics are estimated to enter the ocean each year of 14 million tonnes. 
                    </p>
                    <p class="text-photo" style="animation: slideDownText 1s ease-in-out  forwards;">
                        About 16-35% microplastics released to the oceans are from synthetic textiles as a result of the vast fashion production in the recent times. (www.eea.europa.eu)                    </p>
                    <p class="text-photo" style="animation: slideDownText 1.2s ease-in-out  forwards;">
                        A sustainable fashion production is needed for reducing the release of microplastic toxins to the oceans as well as recycling clothes!
                    </p>
                    <p class="text-photo" style="color:#7335C2; animation: slideDownText 1.5s ease-in-out  forwards;">
                        Irama Kain helps to provide this act for the better and healthier ocean!
                    </p>
                </div>
            </div>
            <div class="donatenow">
                    <a href="{% url 'donation:form-donation' %}" style="color: #7335C2; text-decoration: none;" id="donatenowlink" >Donate Clothes Now</a>
                </div>
            
            <div class = "ongoing-donation" style="display:block; ">
                <a style="text-decoration: none;" data-bs-toggle="collapse" href="#collapseongoing" role="button" aria-expanded="false" aria-controls="collapseongoing">
                    <h2 class="textongoing">
                        My ongoing donation
                    </h2>
                </a>
                <table class="collapse ongoingTable show" id="collapseongoing">
                    
                    <tr id="table-ongoing" class= "mylayout">
                      
                    </tr>   
                    
                </table>

            </div>
            <div class = 'donation-history'>
                <a style="text-decoration: none;" data-bs-toggle="collapse" href="#collapsehistory" role="button" aria-expanded="false" aria-controls="collapsehistory">
                    <h2 class="textongoing" style="color: #3C3C3C; border: 1px solid #3C3C3C; padding-top: 50px;">
                        My donation history
                    </h2>
                </a>
                <table class="collapse ongoingTable" id="collapsehistory" style="margin-bottom: 0px; padding-bottom: 0px;">
                    <tr id="table-history" class= "mylayout">
                    </tr>   
                </table>
                
            </div>
        </div>
        <footer class = "text-center text-lg-start pt-4" style = "background: #F3F3F3;
        background: linear-gradient(0deg, #AAC38A 0%, #F3F3F3 80%); margin-top: 0px;">
            <section class = "">
                <div class = "container text-center text-md-start mt-5">
                    <div class = "row mt-3">
                        <div class="col-md-3 col-lg-4 col-xl-3 ms-5 mb-4" ALIGN = left>
                            <img src="../../static/iramakain.png" height="83px" width="150px" alt="test">
                            <hr>
                            <h6>
                                The era of fashion revolution, The era of sustainable garments.
                            </h6>
                        </div>
                        <div class="col-md-4 col-lg-2 col-xl-2 ms-5 mb-4">
                            <h6 class="text-uppercase fw-bold mb-4">
                                Explore
                                </h6>
                                <p>
                                <a href="{% url 'faq:index' %}" class=" footer-text">F.A.Q</a>
                                </p>
                                <p>
                                <a href="{% url 'donation:show-donation' %}" class=" footer-text">Shop</a>
                                </p>
                                <p>
                                <a href="#" class="footer-text">Donate</a>
                                </p>
                                <p>
                                    <a href="#" class="footer-text">Contact Us</a>
                                </p>
                        </div>
                        <div class="col-md-8 col-lg-3 col-xl-3 ms-auto mb-md-0 mb-4">
                            <!-- Links -->
                            <h6 class="text-uppercase fw-bold mb-4">Our Office</h6>
                            <p><i class="fas fa-home"></i> Fakultas Ilmu Komputer, Universitas Indonesia, Kota Depok, Jawa Barat 16425</p>
                            <p>
                            <i class="fas fa-envelope"></i>
                            cs.ui.ac.id
                            </p>
                            <p><i class="fas fa-phone"></i>  (021) 7863419</p>
                        </div>
                        <div class = 'row row-cols-auto justify-content-center' id = 'row2_footer'>
                            <h6 style = 'margin-left: 40px; margin-bottom: 40px;'>©️ 2022 Copyright: Irama Kain</h6>
                          </div>
                    </div>
                </div>
            </section>
        </footer>
       <!-- TOLONG INI BUAT NAVBAR HARUS DITARO DIBAWAH YA -->
       
    </body>
</html>
{% endblock content %}

donation/templates/notauth.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Donation | Irama Kain</title>
{% endblock meta %}

{% block content %}
<html>
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href= "{% static "/donation/css/notauth.css" %}">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>        
    </head>
    <body>
        <h1>Sorry, you must be authenticated first</h1>
        <a href="{% url 'Authentication:logout-user' %}">Click here to get redirected to Sign In Page</a>
    </body>
</html>
{% endblock content %}