Authentication/urls.py
from django.urls import path, include
from Authentication.views import login_user, register_user, logout_user, get_pengunjung, login_flutter, logout_flutter, register_flutter

app_name = 'Authentication'

urlpatterns = [
    path('login/<str:status>/', login_user, name = 'login-user'),
    path('register/<str:status>', register_user, name = 'register-user'),
    path('logout/', logout_user, name = 'logout-user'),
    path('json/', get_pengunjung, name = 'json'),
    path('login_flutter', login_flutter, name = 'login_flutter'),
    path('logout_flutter', logout_flutter, name = 'logout_flutter'),
    path('register_flutter', register_flutter, name = 'register_flutter'),
]

Home/urls.py
from django.urls import path, include
from Home.views import show_home, show_json

app_name = 'Home'

urlpatterns = [
    path('', show_home, name = 'show_home'),
    path('jsoninfo/', show_json, name = 'show_json'),
]

donation/urls.py
# TODO: Implement Routings Here
from django.urls import path
from .views import *

app_name = 'donation'

urlpatterns = [
    path('', show_donation, name='show-donation'),
    path('form/', form_donation, name='form-donation'),
    path('json/', show_json, name='show_json'),
    path('history/', show_alltime_donation, name='show_alltime_donation'),
    path('done/<int:id>', selesai_donasi, name='done'),
    path('edit/<int:id>', edit_donasi, name='edit'),
    path('edit_flutter/<int:id>', edit_flutter, name='edit_flutter'),
    path('form_flutter/', form_flutter, name='form_flutter'),
    path('current/<int:id>', get_current_donation, name='current'),






]

faq/urls.py
from django.urls import path
from faq.views import *

app_name = 'faq'

urlpatterns = [
    path('', index, name='index'),
    path('create_question/', create_question, name='create_question'),
    path('json/', json, name='json')
]

profilePage/urls.py
from django.urls import path
from .views import *

app_name = 'profilePage'

urlpatterns = [
    path('', lihatProfile, name='lihatProfile'),
    path('edit/', editProfile, name='editProfile'),
    path('get_profile', get_profile, name = 'getProfile'),
    path('edit_flutter', edit_flutter, name = 'editFlutter'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')), #(Steven) gw ngeubah yang tadinya default ke example jadi ke home
    path('Authentication/', include('Authentication.urls')), 
    path('faq/', include('faq.urls')),
    path('profile/', include('profilePage.urls')),
    path('donation/', include('donation.urls')),
    path('marketplace/', include('marketplace.urls')),
    path('partnership/', include('partnership.urls')),
]

# TODO: Implement Routings Here

profilePage/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.core import serializers
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from Authentication.models import Pengunjung
from django.views.decorators.csrf import csrf_exempt


# Create your views here.
@login_required(login_url='../Authentication/login/<str:status>/')
def lihatProfile(request):
    user = request.user
    context = {
        'first_name': user.first_name.upper(),
        'last_name': user.last_name.upper(),
        'email': user.email.lower(),
        'kontak': user.pengunjung.kontak,
        'gender': True if user.pengunjung.jenis_kelamin == "LK" else False,
        'address': user.pengunjung.alamat,
        'poin': user.pengunjung.poin
    }
    return render(request, "lihatProfile.html", context)

@login_required(login_url='../Authentication/login/<str:status>/')
def editProfile(request):
    if request.method == 'POST':
        user = request.user
        pengunjung = Pengunjung.objects.get(user = request.user)
        user.first_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')
        pengunjung.kontak = request.POST.get('kontak')
        if request.POST.get('gender') == 'LK':
            pengunjung.jenis_kelamin = Pengunjung.JenisKelamin.laki_laki
        else:
            pengunjung.jenis_kelamin = Pengunjung.JenisKelamin.perempuan
        pengunjung.alamat = request.POST.get('address')
        user.save()
        pengunjung.save()
        return HttpResponse('Edit user berhasil')
    else:
        return HttpResponseRedirect(reverse('profilePage:lihatProfile'))

@csrf_exempt
def get_profile(request):
    user = request.user
    context = {
        'first_name': user.first_name.upper(),
        'last_name': user.last_name.upper(),
        'email': user.email.lower(),
        'kontak': user.pengunjung.kontak,
        'gender': True if user.pengunjung.jenis_kelamin == "LK" else False,
        'address': user.pengunjung.alamat,
        'poin': user.pengunjung.poin
    }
    return JsonResponse({
        'first_name': user.first_name.upper(),
        'last_name': user.last_name.upper(),
        'email': user.email.lower(),
        'kontak': user.pengunjung.kontak,
        'gender': True if user.pengunjung.jenis_kelamin == "LK" else False,
        'address': user.pengunjung.alamat,
        'poin': user.pengunjung.poin
    }, status=200)

@login_required(login_url='../Authentication/login/<str:status>/')
@csrf_exempt
def edit_flutter(request):
    if request.method == 'POST':
        user = request.user
        pengunjung = Pengunjung.objects.get(user = request.user)
        user.first_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')
        pengunjung.kontak = request.POST.get('kontak')
        if request.POST.get('gender') == 'LK':
            pengunjung.jenis_kelamin = Pengunjung.JenisKelamin.laki_laki
        else:
            pengunjung.jenis_kelamin = Pengunjung.JenisKelamin.perempuan
        pengunjung.alamat = request.POST.get('address')
        user.save()
        pengunjung.save()
        return JsonResponse({
                "status": True,
                "message": "Successfully added donation"
                }, status=200)
    else:
        return JsonResponse({
                "status": False,
                "message": "401 Error"
                }, status=401)

profilePage/templates/editProfile.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Profile</title>
{% endblock meta %}

{% block content %}
<html>
    <head>

    </head>
    <body>
        <h1>
            Ini edit profile
        </h1>
    </body>
</html>
{% endblock content %}

profilePage/templates/lihatProfile.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Profile | Irama Kain</title>
{% endblock meta %}

{% block content %}
<html>
    <head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href= "{% static "/profile/css/style.css" %}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    </head>
    <script>
        $(document).ready(function(){
            $('#buttonEdit').click(function(){
                $.ajax({
                   url: "{% url 'profilePage:editProfile' %}",
                   type: "POST",
                   data: {
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                    'first_name': $('#form_first_name').val(),
                    'last_name': $('#form_last_name').val(),
                    'kontak': $('#form_kontak').val(),
                    'gender': $('.form-check input:radio:checked').val(),
                    'address': $('#form_address').val()
                   },
                   success: function(data){
                        alert(data);
                        $('#id_first_name').html($('#form_first_name').val().toUpperCase());
                        $('#id_last_name').html($('#form_last_name').val().toUpperCase());
                        $('#id_kontak').html($('#form_kontak').val());
                        if ($('.form-check input:radio:checked').val() == "LK"){
                            $('#id_gender').html('Laki-Laki');
                        }
                        else{
                            $('#id_gender').html('Perempuan');
                        }
                        $('#id_address').html($('#form_address').val());
                   }
                });
            });
        });
    </script>
    <body>
        <!-- TODO: BACKEND STEVEN -->
        <script>

        </script>
        <div class="navprofile">
            <div class="d-flex mb-3" id = "flexnav">
                <div class="me-auto p-2 navp-content">
                    <a href="{% url 'Home:show_home' %}" style="text-decoration:none; " >
                    <div class="container">
                        <img src="../static/profile/img/back.png" width="15px" height="20px">
                        <p class="text" style="display:inline; color: white;">Back to Home</p>
                    </div>
                    </a>
                    
                </div>
                <a href="{% url 'donation:show-donation' %} " id="linkdonasi" style="text-decoration:none;">
                    <div class="p-2 navp-content">My Donation</div>
                </a>
                <div id="linkcart" class="p-2 navp-content">My Cart</div >
                <a href="{% url 'Authentication:logout-user' %}" id="linkout" style="text-decoration:none;">
                    <div class="p-2 navp-content">Sign Out</div>
                </a>
            </div>
        </div> 
        <div class="myprofilediv">
            <h2 class="textjudul">
                My Profile
            </h2>
        </div>
        
        <div class= "profilebox">
            <div class="mydetails">
                <h3 class="textdetails" style="padding-bottom:30px">My Details</h3>
                <div class="row" id="detailscontent">
                    <div class="col">
                       <h5 class="judul">First Name</h5>
                        <p class="isi" id = 'id_first_name'>{{first_name}}</p> 
                        <hr width = 70% style= "color: black;">
                    </div>
                    <div class="col">
                        <h5 class="judul"> Last Name</h5>
                        <p class="isi" id= 'id_last_name'>{{last_name}}</p>
                        <hr width = 70% style= "color: black;">
                    </div class="col">
                    <div class="w-100"></div>
                    <div class="col">
                        <h5 class="judul">Email</h5>
                        <p class="isi" id = 'id_email'>{{email}}</p>
                        <hr width = 70% style= "color: black;">
                    </div>
                    <div class="col">
                        <h5 class="judul">Gender</h5>
                        {% if gender %}
                            <p class="isi" id = 'id_gender'>Laki-Laki</p>
                        {% else %}
                            <p class="isi" id = 'id_gender'>Perempuan</p>
                        {% endif %}
                        <hr width = 70% style= "color: black;">
                    </div>
                    <div class="w-100"></div>
                    <div class="col">
                        <h5 class="judul ">Contacts</h5>
                        <p class="isi" id = 'id_kontak'>{{kontak}}</p>
                        <hr width = 70% style= "color: black;">
                    </div>
                    <div class="col">
                        <h5 class="judul ">Address</h5>
                        <p class="isi " id = 'id_address'>{{address}}</p>   
                        <hr width = 70% style= "color: black;">  
                    </div>
                </div>
                <div class="divbutton" id = 'edit_button'>
                    <button class="edit" data-bs-toggle="modal" data-bs-target="#myModal"><p class="edittext">Edit Profile</p></button>
                </div>
  
                <!-- Modal -->
                <div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h1 class="modal-title fs-5" id="createTaskModal">Edit Profile</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <form id = "newForm">
                                {% csrf_token %}
                                <label class = "col-form-label">First Name</label>
                                <input type = "text" class = "form-control" id = form_first_name value = '{{first_name}}'>
                                <label class = "col-form-label">Last Name</label>
                                <input type = "text" class = "form-control" id = form_last_name value = '{{last_name}}'>
                                <label class = "col-form-label">Contacts</label>
                                <input type = "text" class = "form-control" id = form_kontak value = '{{kontak}}'>
                                <label class = "col-form-label">Gender</label>
                                <div class="form-check">
                                    {% if gender %}
                                        <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioLK" value = "LK" checked>
                                    {% else %}
                                        <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioLK" value = "LK">
                                    {% endif %}
                                    <label class="form-check-label" for="flexRadioLK">
                                      Laki-Laki
                                    </label>
                                </div>
                                <div class="form-check">
                                    {% if gender == False %}
                                        <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioPP" value = "PP" checked>
                                    {% else %}
                                        <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioPP" value = "PP">
                                    {% endif %}
                                    <label class="form-check-label" for="flexRadioPP">
                                      Perempuan
                                    </label>
                                </div>
                                
                                <label class = "col-form-label">Address</label>
                                <input type = "text" class = "form-control" id = form_address value = '{{address}}'>
                            </form>
                        </div>
                        <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary" id="buttonEdit">Save changes</button>
                        </div>
                    </div>
                    </div>
                </div>
            </div> 
            <div class="mypoints"> 
                <h3 class="textdetails">My Points</h3>
                <div class="row">
                    <div class="containers col">
                        <img src="../static/profile/img/Coins.png" id="logoCoin" style= "padding-bottom: 10px; text-align: center; width: 25px; height: 35px">
                        <p class="judul" id="textpoin" style="display:inline;">Donation Points</p>
                    </div>
                    <p class="isi col">{{poin}}</p>    
                </div>
                <hr style= "color: black;">
            </div> 
        </div>
    </body>
</html>
{% endblock content %}