Authentication/urls.py
from django.urls import path, include
from Authentication.views import login_user, register_user, logout_user, get_pengunjung, login_flutter, logout_flutter, register_flutter

app_name = 'Authentication'

urlpatterns = [
    path('login/<str:status>/', login_user, name = 'login-user'),
    path('register/<str:status>', register_user, name = 'register-user'),
    path('logout/', logout_user, name = 'logout-user'),
    path('json/', get_pengunjung, name = 'json'),
    path('login_flutter', login_flutter, name = 'login_flutter'),
    path('logout_flutter', logout_flutter, name = 'logout_flutter'),
    path('register_flutter', register_flutter, name = 'register_flutter'),
]

Home/urls.py
from django.urls import path, include
from Home.views import show_home, show_json

app_name = 'Home'

urlpatterns = [
    path('', show_home, name = 'show_home'),
    path('jsoninfo/', show_json, name = 'show_json'),
]

donation/urls.py
# TODO: Implement Routings Here
from django.urls import path
from .views import *

app_name = 'donation'

urlpatterns = [
    path('', show_donation, name='show-donation'),
    path('form/', form_donation, name='form-donation'),
    path('json/', show_json, name='show_json'),
    path('history/', show_alltime_donation, name='show_alltime_donation'),
    path('done/<int:id>', selesai_donasi, name='done'),
    path('edit/<int:id>', edit_donasi, name='edit'),
    path('edit_flutter/<int:id>', edit_flutter, name='edit_flutter'),
    path('form_flutter/', form_flutter, name='form_flutter'),
    path('current/<int:id>', get_current_donation, name='current'),






]

faq/urls.py
from django.urls import path
from faq.views import *

app_name = 'faq'

urlpatterns = [
    path('', index, name='index'),
    path('create_question/', create_question, name='create_question'),
    path('json/', json, name='json')
]

partnership/urls.py
from django.urls import path
from partnership.views import CommentView, CommentDataView

app_name = 'partnership'

urlpatterns = [
    path('', CommentView.as_view(), name="comment"),
    path('view', CommentDataView.as_view(), name="comment_data")
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')), #(Steven) gw ngeubah yang tadinya default ke example jadi ke home
    path('Authentication/', include('Authentication.urls')), 
    path('faq/', include('faq.urls')),
    path('profile/', include('profilePage.urls')),
    path('donation/', include('donation.urls')),
    path('marketplace/', include('marketplace.urls')),
    path('partnership/', include('partnership.urls')),
]

# TODO: Implement Routings Here

partnership/models.py
from unittest.util import _MAX_LENGTH
from django.db import models
from django.contrib.auth.models import User

class DataPartner(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, default = None)
    nama_depan = models.TextField()
    nama_belakang = models.TextField()
    email_user = models.EmailField()
    nomor_user = models.IntegerField()
    pesan_user = models.TextField()
    
class Comment(models.Model):
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

partnership/forms.py
from email.message import Message
from django import forms
from partnership.models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["comment"]

partnership/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.template import loader
from django.views import View
from partnership.forms import CommentForm
from partnership.models import Comment

class CommentView(View):
    form_class = CommentForm
    def get(self, request, *args, **kwargs):
        return render(request, "partnership.html", {})

    def post(self, request, *args, **kwargs):
        if request.is_ajax():
            form = self.form_class(request.POST)
            if form.is_valid():
                form.save()
                return JsonResponse({'message': 'success'})
            return JsonResponse({'message': 'field couldn\'t validate'})
        return JsonResponse({'message': 'Wrong request'})

class CommentDataView(View):
    def get(self, request, *args, **kwargs):
        template = loader.get_template("partnership_view.html")
        comments = Comment.objects.all()
        context = {
            "comment_list": comments
        }
        return HttpResponse(template.render(context, self.request))

partnership/templates/partnership.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <title>Partnership | Irama Kain</title>
{% endblock meta %}

{% block content %}
<html>
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href= "{% static "/partnership/css/style.css" %}">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'Home:show_home' %}">Irama Kain</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'donation:show-donation' %} ">Donations</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Shop</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'faq:index' %}" >F.A.Q</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Contact Us</a>
                  </li>
                </ul>
                <div class="d-flex">
                    <a class="nav-link" href="#" style="margin-right: 20px">
                        <img class="me-2 p-2 nav-item" src="../static/donation/img/cart.png" style="width: 40px; height:40px; ">
                    </a>
                    <div class="containers col p-2" style="padding-top: 12px; margin-left: 10px; margin-right: 30px;">
                        <img src="../static/profile/img/Coins.png" style="display: inline; width: 25px; height: 25px; margin-bottom: 10px">
                        <p class="nav-link" style="display: inline; font-size: 16px;">{{poin}}</p>
                    </div>
                    <a class="p-2 nav-link" href="{% url 'Authentication:logout-user' %}">Sign Out</a>
                </div>
              </div>
            </div>
        </nav>
        <section>
         <div>
            <div class="row">
                <h1 class="header">Keep in touch</h1>
                <p class="subheader">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                <p> </p>
            </div>
            <div class="container1">
                <div class="contactInfo">
                    <div>
                        <h2>Contact Info</h2>
                        <ul class="info">
                            <li>
                                <span><img src="../static/partnership/img/location.png"></span>
                                <span>Pondok Cina, Kecamatan Beji, Kota Depok, Jawa Barat 16424</span>
                            </li>
                            <li>
                                <span><img src="../static/partnership/img/Message.png"></span>
                                <span>lorem@ipsum.com</span>
                            </li>
                            <li>
                                <span><img src="../static/partnership/img/Call.png"></span>
                                <span>+6287343486023</span>
                            </li>
                        </ul>
                    </div>
                    <ul class="sci">
                        <li><a href="#"><img src="../static/partnership/img/Facebook.png"></a></li>
                        <li><a href="#"><img src="../static/partnership/img/Instagram.png"></a></li>
                        <li><a href="#"><img src="../static/partnership/img/Twitter.png"></a></li>
                    </ul>
                </div>

                <div class="contactForm">
                    <h2>Send us a Message</h2>
                    <div class="formBox">
                        <div class="inputBox w50">
                            <input type="text" required>
                            <span>First Name</span>
                        </div>
                        <div class="inputBox w50">
                            <input type="text" required>
                            <span>Last Name</span>
                        </div>
                        <div class="inputBox w50">
                            <input type="email" required>
                            <span>Email Address</span>
                        </div>
                        <div class="inputBox w50">
                            <input type="text" required>
                            <span>Phone Number</span>
                        </div>
                        <span>Message</span>
                        <div class="inputBox w100">
                            <form action="formComment" aria-roledescription="{% url 'partnership:comment' %}" autocomplete="off">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col 12">
                                        <div class="form-group validate">
                                            <textarea class="form-control" name="comment"></textarea>
                                        </div>
                                    </div>                   
                                </div>
                            </form>
                        </div>
                        <div class="inputBox w100">
                            <input type="submit" class="btn btn-primary pl-5 pr-5 btnSave" value="Send">
                        </div>
                    </div>
                </div>
            </div>

            <div class="container2">
                <div class="messageUser">
                    <h2>Your Message</h2>
                    <div class="comment-context mt-5" data-url="{% url 'partnership:comment_data' %}"></div>
                </div>
            </div>
            
         </div>
        </section>
        <footer class = "text-center text-lg-start pt-4" style = "background: #F3F3F3;
        background: linear-gradient(0deg, #AAC38A 0%, #F3F3F3 80%); margin-top: 50px;">
            <section class = "">
                <div class = "container text-center text-md-start mt-5">
                    <div class = "row mt-3">
                        <div class="col-md-3 col-lg-4 col-xl-3 ms-5 mb-4" ALIGN = left>
                            <img src="../static/partnership/iramakain.png" height="83px" width="150px" alt="test">
                            <hr>
                            <h6>
                                The era of fashion revolution, The era of sustainable garments.
                            </h6>
                        </div>
                        <div class="col-md-4 col-lg-2 col-xl-2 ms-5 mb-4">
                            <h6 class="text-uppercase fw-bold mb-4">
                                Explore
                                </h6>
                                <p>
                                <a href="{% url 'faq:index' %}" class=" footer-text">F.A.Q</a>
                                </p>
                                <p>
                                <a href="{% url 'donation:show-donation' %}" class=" footer-text">Shop</a>
                                </p>
                                <p>
                                <a href="#" class="footer-text">Donate</a>
                                </p>
                                <p>
                                    <a href="#" class="footer-text">Contact Us</a>
                                </p>
                        </div>
                        <div class="col-md-8 col-lg-3 col-xl-3 ms-auto mb-md-0 mb-4">
                            <!-- Links -->
                            <h6 class="text-uppercase fw-bold mb-4">Our Office</h6>
                            <p><i class="fas fa-home"></i> Fakultas Ilmu Komputer, Universitas Indonesia, Kota Depok, Jawa Barat 16425</p>
                            <p>
                            <i class="fas fa-envelope"></i>
                            cs.ui.ac.id
                            </p>
                            <p><i class="fas fa-phone"></i>  (021) 7863419</p>
                        </div>
                        <div class = 'row row-cols-auto justify-content-center' id = 'row2_footer'>
                            <h6 style = 'margin-left: 40px; margin-bottom: 40px;'>©️ 2022 Copyright: Irama Kain</h6>
                          </div>
                    </div>
                </div>
            </section>
        </footer>
    </body>
</html>

{% endblock content %}

{% block scripts %}
<script>
    function getComments(){
        $ajax({
            url: $(".comment-content").data('url'),
            type: "GET",
            success: function(resp){
                $(".comment-content").html(resp);
            },
            error: function(resp){
                console.log("something went wrong");
            }
        });
    }
    getComments();
    $("formComment").on("submit", function(e){
        e.preventDefault();
        e.stopPropagation();
        var $this = $(this);
        var valid = true;
        $('#formComment textarea').each(function(){
            let $this = $(this)

            if(!$this.val()){
                valid = false;
                $this.parents('.validate').find('.mySpan').text('The '+$this.attr('name').replace(/[\_]+/g, ' '))
            }
        });

        if(valid){
            $(".btnSave").text('Saving...').attr('disabled',true);
            let data = $this.serialize();
        ajax({
            url: $this.attr('action'),
            type: "POST",
            dataType: 'json',
            success: function(resp){
                if(resp.message === 'success'){
                    getComments();
                } else{
                    alert(resp.message);
                }
            },
            error: function(resp){
                console.log('somethin went wrong');
            }
        });
        }
        return false
    });
</script>
{% endblock scripts %}

partnership/templates/partnership_view.html
<div>
    {% for comment in comment list %}
        <p>{{ partnership:comment }}</p>
        <hr>
    {% endfor %}
</div>